# Copyright (c) 2018, Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.

FROM oraclelinux:7-slim

RUN yum install --enablerepo ol7_optional_latest -y \
    make \
    git \
    golang \
    && rm -rf /var/cache/yum/*
