# Copyright (c) 2018, Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.

FROM ubuntu:16.04

COPY graphpipe-batcher /
ENTRYPOINT ["/graphpipe-batcher"]
